In [2]:
# 1
# 아래 1차원 리스트는 학생 5명이 4개 과목(국어, 영어, 수학, 과학 순)에서 받은 점수를 이어 붙인 것입니다.

# Numpy만 사용하여(반복문 사용 금지) 다음을 순서대로 수행하고 결과를 출력하세요.
import numpy as np
scores = [88, 92, 79, 95,
          75, 68, 82, 70,
          92, 99, 95, 88,
          60, 72, 65, 58,
          85, 80, 78, 90]

In [3]:
# 위 리스트를 5행 4열 ndarray로 변환하고 shape, ndim, size, dtype을 출력하시오.
scores=np.array(scores).reshape(5,4)
print(scores)
print(scores.shape, scores.ndim, scores.size, scores.dtype)

[[88 92 79 95]
 [75 68 82 70]
 [92 99 95 88]
 [60 72 65 58]
 [85 80 78 90]]
(5, 4) 2 20 int64


In [4]:
# 학생 별 평균과 과목 별 평균을 각각 구하시오.
student=[np.mean(scores[:1]),np.mean(scores[1:2]),np.mean(scores[2:3]),np.mean(scores[3:4]),np.mean(scores[4:5])]
student=np.array(student)
print(student)

subject=[np.mean(scores[:,:1]),np.mean(scores[:,1:2]),np.mean(scores[:,2:3]),np.mean(scores[:,3:4])]
subject=np.array(subject)
print(subject)

[88.5  73.75 93.5  63.75 83.25]
[80.  82.2 79.8 80.2]


In [ ]:
# 전체에서 가장 높은 점수와 그 점수가 몇 번째 학생·몇 번째 과목인지 구하시오.
print(np.max(scores))
print(np.argmax(scores))
print(np.where(scores==np.max(scores)))

99
9
(array([2]), array([1]))


In [9]:
# 전체 평균, 표준편차, 분산을 구하시오.
print(np.mean(scores),np.std(scores),np.var(scores))

80.55 11.825713509129164 139.84750000000003


In [ ]:
# 평균이 80점 이상인 학생의 인덱스와 인원수를 구하고, 해당 학생들의 성적만 잘라내어 출력하시오.

print(np.where(student>=80))

(array([0, 2, 4]),)


In [ ]:
# 90점 이상인 점수의 개수, 100점 이상인 점수가 하나라도 있는지, 모든 점수가 60점 이상인지를 판별하시오.



In [ ]:
# 90점 이상은 'A', 80점 이상은 'B', 나머지는 'C'로 변환한 등급 배열을 만드시오.



In [ ]:
# 2
# 0~255 사이의 정수 난수로 이루어진 8행 8열 배열을 흑백 이미지 데이터라고 가정합니다. 채점 결과를 동일하게 맞추기 위해 반드시 아래 시드를 먼저 실행하세요.

import numpy as np
np.random.seed(2024)
img = np.random.randint(0, 256, size=(8, 8))

In [ ]:
# 생성한 img를 출력하시오.

# 이미지 정중앙의 4×4 영역만 잘라내어 출력하시오.



In [ ]:
# 짝수 번째 행(0, 2, 4, 6행)만 뽑아내시오.



In [ ]:
# 128 이상인 픽셀은 255(흰색), 미만인 픽셀은 0(검은색)으로 바꾼 이진화 배열을 만드시오.



In [ ]:
# 이진화 결과에서 흰색 픽셀과 검은색 픽셀의 개수를 각각 세시오.



In [ ]:
# 원본 이미지를 좌·우 절반으로 분할하시오.



In [ ]:
# 분할한 두 조각의 순서를 바꿔 다시 이어 붙여 좌우가 뒤바뀐 이미지를 만드시오.



In [ ]:
# 원본 이미지를 1차원으로 펼친 뒤 앞 10개 값과 shape을 출력하시오.



In [ ]:
# 128 이상인 픽셀만 골라내어 그 개수와 평균값을 구하시오.



In [ ]:
# 3
# 3개 지점이 4개 제품을 판매한 수량과, 제품별 단가가 다음과 같습니다.

sales = np.array([[120,  80,  45,  60],     # A지점
                  [200, 150,  90,  30],     # B지점
                  [ 75,  60, 120,  95]])    # C지점
price = np.array([1500, 3000, 5000, 2000])  # 제품 1~4 단가

In [ ]:
# 브로드캐스트를 이용해 각 지점의 제품별 매출액(수량 × 단가) 행렬을 구하시오. (반복문 금지)



In [ ]:
# 행렬곱을 이용해 각 지점의 총매출을 한 번에 구하시오. 또한 제품별 총판매량도 구하시오.



In [ ]:
# 각 제품의 평균 판매량을 구한 뒤, 브로드캐스트로 평균 대비 편차 행렬을 구하시오.



In [ ]:
# 각 지점을 기준으로 판매량을 정규화하시오. 결과의 행별 평균이 0, 표준편차가 1이 되는지 확인하시오.



In [ ]:
# sales의 전치행렬을 구하고 shape을 출력하시오.



In [ ]:
# sales의 앞 3개 열만 잘라 3×3 정방행렬 A를 만들고, 행렬식과 역행렬을 구하시오. 이어서 A와 역행렬을 곱해 단위행렬이 나오는지 확인하시오.



In [ ]:
# 총매출이 가장 높은 지점의 인덱스와, 지점 순서대로의 누적 매출을 구하시오.

