In [1]:
%pip install numpy

  Using cached numpy-2.5.1-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.5.1-cp312-cp312-win_amd64.whl (12.4 MB)
Note: you may need to restart the kernel to use updated packages.


In [ ]:
# !pip install numpy -> 옛날 방식 (잘못된 가상환경에 설치될 위험 있음)

In [2]:
import numpy as np

In [7]:
matrix_1 = [
    [1, 2], 
    [3, 4]
]
matrix_2 = [
    [5, 6],
    [7, 8]
]
# 행렬 더하기
[
    [6, 8],
    [10, 12]
]

matrix_1 + matrix_2 # concat
result = []
for i in range(len(matrix_1)): # 행 인덱스
    temp = []
    for j in range(len(matrix_1[i])): # 열 인덱스
        # print(matrix_1[i][j], matrix_2[i][j])
        # temp에 더한 값을 append 해준다.
        temp.append(matrix_1[i][j] + matrix_2[i][j])
    # result에 temp(행 단위로 더한 리스트를) append한다.
    result.append(temp)
result

[[6, 8], [10, 12]]

In [8]:
# 모든 원자에 1씩 더하기
result = []
for i in range(len(matrix_1)): # 행 인덱스
    temp = []
    for j in range(len(matrix_1[i])): # 열 인덱스
        temp.append(matrix_1[i][j] + 1)
    result.append(temp)
result

[[2, 3], [4, 5]]

In [10]:
# numpy 숫자 계산을 쓴다 -> numpy 배열로 바꿔주는게 필요함
array_1 = np.array(matrix_1)
array_2 = np.array(matrix_2)
# arr
array_1, type(array_1)

(array([[1, 2],
        [3, 4]]),
 numpy.ndarray)

In [16]:
array_1 + array_2

array([[ 6,  8],
       [10, 12]])

In [ ]:
array_1 + 1 # 브로드캐스팅 (차원이 다른 배열끼리의 연산)

array([[2, 3],
       [4, 5]])

In [ ]:
import time
size = 10000000

# list
x = list(range(size))
y = list(range(size))
start_time = time.time()
z = [ x[i]+y[i] for i in range(size) ]
print('리스트 걸린시간', time.time() - start_time)

# adlist
x = np.arange(size)
y = np.arange(size)
start_time = time.time()
z = x+y
print('넘파이 걸린시간', time.time() - start_time)

리스트 걸린시간 1.10941743850708
넘파이 걸린시간 0.34490275382995605


In [ ]:
# int[]
# C를 바탕으로 작성된 패키지 -> 자료형을 설정, 배열에 자료형이 종속됨


dtype('int64')

In [30]:
x = np.uint( 32 ) # 0차원 값

In [32]:
x.dtype

dtype('uint64')

In [36]:
x = np.array([1, 2, 3, 4])
x.dtype
x

array([1, 2, 3, 4])

In [37]:
x = np.float32(x)
x

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
x = np.array([1, 2, 3, 4], dtype=np.float32)
x

# AI 쪽에서는 가중치 -> 연산의 정확도 -> float32, float64

array([1., 2., 3., 4.], dtype=float32)

In [40]:
x = np.array(1)
x.ndim, x.shape, x.size

(0, (), 1)

In [41]:
x = np.array([1, 2])
x.ndim, x.shape, x.size

(1, (2,), 2)

In [42]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x.ndim, x.shape, x.size

(2, (2, 3), 6)

In [50]:
x = np.arange(10, 1, -0.5)
x

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5])

In [ ]:
# list(range(10.0)) 안됨

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
x = np.linspace(1, 10, 200, endpoint=True)
x

In [ ]:
%pip install matplotlib

In [ ]:
import matplotlib.pyplot as plt

# x = np.array([1, 2, 3])
x = np.linspace(-5, 5, 50)
y = x**2
plt.plot(x, y)

In [76]:
x = np.arange(12).reshape( (2, -1, 3) )
x

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
x = np.array([
    [1, 2], 
    [3, 4], 
    [5, 6]
])

x.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x = np.arange(20)
x[1:3]

array([1, 2])

In [86]:
x = x.reshape( (4, 5) )
x[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [91]:
x = np.arange(30).reshape( (2, 5, 3) )
x[:, 2:4, ::2]

array([[[ 6,  8],
        [ 9, 11]],

       [[21, 23],
        [24, 26]]])

In [96]:
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [99]:
x[1][2][1]
x[1, 2, 1]

np.int64(22)

In [ ]:
my_list = [[[0] * 3 for _ in range(5)] for _ in range(2)]
# my_list[1, 2, 1]

In [107]:
x = np.arange(20).reshape((4, 5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [109]:
x[x > 3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [113]:
x[~(x == 1)]

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [121]:
x[(x > 3) & (x < 8)]

array([4, 5, 6, 7])

In [123]:
(x > 15) | (x < 8)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [128]:
x = np.random.rand(5, 5) # 0 ~ 1
# 5 ~ 13
x * 8 + 5 # 0 ~ 8 -> 5 ~ 13

array([[ 8.07509958,  8.75562908, 12.86559267,  6.41376394,  7.05485195],
       [10.88766796, 11.93280701, 11.82389894, 11.56971046,  8.10218002],
       [ 9.68360675,  9.58385049, 11.28475579,  5.31657448, 11.18069855],
       [ 5.99560685, 12.12839639, 10.99069925,  7.51022816,  7.52146815],
       [11.98905508, 11.48332235,  6.87947424, 11.37973379,  5.47412553]])

In [187]:
x = np.random.randint(1, 10, size=(5, 5))

In [188]:
x

array([[4, 8, 1, 1, 1],
       [7, 5, 3, 7, 6],
       [4, 3, 3, 4, 9],
       [5, 7, 8, 8, 6],
       [3, 8, 7, 6, 5]], dtype=int32)

In [190]:
np.ones( [5, 5] )
np.zeros( [5, 5] )
np.eye( 5 )

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [193]:
x

array([[4, 8, 1, 1, 1],
       [7, 5, 3, 7, 6],
       [4, 3, 3, 4, 9],
       [5, 7, 8, 8, 6],
       [3, 8, 7, 6, 5]], dtype=int32)

In [199]:
x.ravel()

array([4, 8, 1, 1, 1, 7, 5, 3, 7, 6, 4, 3, 3, 4, 9, 5, 7, 8, 8, 6, 3, 8,
       7, 6, 5], dtype=int32)

In [ ]:
x = np.arange(1, 4)
y = np.arange(4, 7)
x, y

(array([1, 2, 3]), array([4, 5, 6]))

In [205]:
np.concat([x, y])

array([1, 2, 3, 4, 5, 6])

In [206]:
x = np.arange(10).reshape((2, 5))
y = np.arange(10, 20).reshape( (2, 5))
x, y

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]))

In [210]:
np.concat( [x, y], axis=1 )

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [219]:
x.shape

(2, 5)

In [218]:
np.split(x, 5, axis=1)

[array([[0],
        [5]]),
 array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]])]

In [228]:
x = np.arange(5)
x % 3

array([0, 1, 2, 0, 1])

In [ ]:
x = np.arange(9).reshape(3, 3)
x

y = np.arange(3)
x, y

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([0, 1, 2]))

In [231]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [234]:
x = np.arange(3).reshape(3, 1)
x, y

(array([[0],
        [1],
        [2]]),
 array([0, 1, 2]))

In [237]:
x + y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [240]:
x = np.arange(4).reshape(2, 2)
y = np.arange(4).reshape(2, 2) + 4
x, y

(array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]]))

In [242]:
x @ y

array([[ 6,  7],
       [26, 31]])

In [243]:
x.dot(y)

array([[ 6,  7],
       [26, 31]])

In [ ]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [248]:
x.T

array([[0, 2],
       [1, 3]])

In [249]:
np.linalg.inv(x)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [250]:
np.linalg.det(x)

np.float64(-2.0)

In [252]:
x

array([[0, 1],
       [2, 3]])

In [255]:
# np.mean(x)
x.mean(axis=1)

array([0.5, 2.5])

In [ ]:
np.median(x) # 중앙값

np.float64(1.5)

In [265]:
x.std()

np.float64(1.118033988749895)

In [266]:
x.var()

np.float64(1.25)

In [267]:
x.sum(axis=1)

array([1, 5])

### 실습 01

In [268]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y = x * 10 # np.arange(10, 100, 10)
y

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [276]:
x = x.reshape(3, 3)
y = y.reshape(3, 3)

In [278]:
x + y

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [279]:
x * y

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [282]:
x @ y

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

### 실습 02

In [284]:
x = np.linspace(1, 20, 30)
x + 10

array([11.        , 11.65517241, 12.31034483, 12.96551724, 13.62068966,
       14.27586207, 14.93103448, 15.5862069 , 16.24137931, 16.89655172,
       17.55172414, 18.20689655, 18.86206897, 19.51724138, 20.17241379,
       20.82758621, 21.48275862, 22.13793103, 22.79310345, 23.44827586,
       24.10344828, 24.75862069, 25.4137931 , 26.06896552, 26.72413793,
       27.37931034, 28.03448276, 28.68965517, 29.34482759, 30.        ])

### 실습 03

In [300]:
# 난수배열 고정
np.random.seed(5)
x = np.random.randint(1, 100, size=(2, 10, 10))
x

array([[[79, 62, 17, 74,  9, 63, 28, 31, 81,  8],
        [77, 16, 54, 81, 28, 45, 78, 76, 66, 48],
        [31, 85, 87, 19, 10, 42, 63,  2, 83, 17],
        [79,  6, 59,  1, 81,  5, 37, 52, 28, 32],
        [ 3, 69, 39, 84, 20, 19,  8, 31, 63, 12],
        [68, 66, 56,  4, 92, 79, 28, 30, 34, 90],
        [86,  8, 17, 95, 15, 91, 32, 10, 39, 48],
        [17,  6, 35, 46, 60, 25, 14, 32, 33, 77],
        [45,  6, 15, 48, 95, 83,  1,  8, 87, 17],
        [65,  9, 91, 45, 38, 95, 76,  6, 23, 53]],

       [[70, 83, 61, 92, 30, 89, 98, 93, 80, 71],
        [36, 21, 50, 73, 33, 83, 14, 93, 19, 53],
        [82, 23, 59, 84, 93, 84, 50,  5, 83, 37],
        [42, 21, 33, 11, 32, 16, 23, 71, 10, 64],
        [95, 15, 67, 58, 20, 65,  9,  9, 72, 13],
        [21, 60, 73, 75, 87, 73, 33, 16, 70, 36],
        [63, 44,  1,  3,  3, 92, 66, 46, 88,  2],
        [24, 51, 87, 20, 55, 25, 65, 78, 74,  2],
        [10, 65, 24, 40, 69, 82, 92, 37, 98, 88],
        [70, 37, 19, 35, 31, 78, 98, 36, 30,  2]

In [ ]:
x[x >= 50] = 1
x[x < 50] = 2

array([[[ 1,  1, 17,  1,  9,  1, 28, 31,  1,  8],
        [ 1, 16,  1,  1, 28, 45,  1,  1,  1, 48],
        [31,  1,  1, 19, 10, 42,  1,  2,  1, 17],
        [ 1,  6,  1,  1,  1,  5, 37,  1, 28, 32],
        [ 3,  1, 39,  1, 20, 19,  8, 31,  1, 12],
        [ 1,  1,  1,  4,  1,  1, 28, 30, 34,  1],
        [ 1,  8, 17,  1, 15,  1, 32, 10, 39, 48],
        [17,  6, 35, 46,  1, 25, 14, 32, 33,  1],
        [45,  6, 15, 48,  1,  1,  1,  8,  1, 17],
        [ 1,  9,  1, 45, 38,  1,  1,  6, 23,  1]],

       [[ 1,  1,  1,  1, 30,  1,  1,  1,  1,  1],
        [36, 21,  1,  1, 33,  1, 14,  1, 19,  1],
        [ 1, 23,  1,  1,  1,  1,  1,  5,  1, 37],
        [42, 21, 33, 11, 32, 16, 23,  1, 10,  1],
        [ 1, 15,  1,  1, 20,  1,  9,  9,  1, 13],
        [21,  1,  1,  1,  1,  1, 33, 16,  1, 36],
        [ 1, 44,  1,  3,  3,  1,  1, 46,  1,  2],
        [24,  1,  1, 20,  1, 25,  1,  1,  1,  2],
        [10,  1, 24, 40,  1,  1,  1, 37,  1,  1],
        [ 1, 37, 19, 35, 31,  1,  1, 36, 30,  2]

In [299]:
x

array([[[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]], dtype=int32)