In [1]:
import numpy as np

In [2]:
sales = np.array([[120,  80,  45,  60],     # A지점
                  [200, 150,  90,  30],     # B지점
                  [ 75,  60, 120,  95]])    # C지점
price = np.array([1500, 3000, 5000, 2000])  # 제품 1~4 단가

브로드캐스트를 이용해 각 지점의 제품별 매출액(수량 × 단가) 행렬을 구하시오. (반복문 금지)

In [ ]:
sales * price # (3, 4) / (4, )

array([[180000, 240000, 225000, 120000],
       [300000, 450000, 450000,  60000],
       [112500, 180000, 600000, 190000]])

행렬곱을 이용해 각 지점의 총매출을 한 번에 구하시오. 또한 제품별 총판매량도 구하시오.


In [8]:
# 행렬곱을 이용해 각 지점의 총매출
sales @ price

# 제품 별 총 판매량
sales.sum(axis=0)

array([395, 290, 255, 185])

In [7]:
sum(sales[0] * price)

np.int64(765000)

각 제품의 평균 판매량을 구한 뒤, 브로드캐스트로 평균 대비 편차 행렬을 구하시오.

In [12]:
sales - sales.mean(axis=0)

array([[-11.66666667, -16.66666667, -40.        ,  -1.66666667],
       [ 68.33333333,  53.33333333,   5.        , -31.66666667],
       [-56.66666667, -36.66666667,  35.        ,  33.33333333]])

각 지점을 기준으로 판매량을 정규화하시오. 결과의 행별 평균이 0, 표준편차가 1이 되는지 확인하시오.

In [15]:
sales

array([[120,  80,  45,  60],
       [200, 150,  90,  30],
       [ 75,  60, 120,  95]])

In [20]:
# 정규화
# (값 - 평균) / 표준편차

# 지점별 평균
# 지점별 표준편차
sales.mean(axis=1)
sales.std(axis=1)

            # (3, 4)    # (3, ) -> (3, 1)
sales_norm = (sales - sales.mean(axis=1).reshape(-1, 1)) / sales.std(axis=1).reshape(-1, 1)
sales_norm

array([[ 1.55440457,  0.13323468, -1.11028898, -0.57735027],
       [ 1.29337197,  0.50951017, -0.43112399, -1.37175815],
       [-0.55555556, -1.22222222,  1.44444444,  0.33333333]])

In [ ]:
sales_norm.mean(axis=1)
sales_norm.std(axis=1)

array([1., 1., 1.])

In [ ]:
# 1차원에는 Transpose 불가
sales_norm = (sales.T - sales.mean(axis=1)) / sales.std(axis=1)
# sales_norm = sales_norm.T

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

sales의 전치행렬을 구하고 shape을 출력하시오.

In [30]:
sales.T.shape

(4, 3)

sales의 앞 3개 열만 잘라 3×3 정방행렬 A를 만들고, 행렬식과 역행렬을 구하시오. 

이어서 A와 역행렬을 곱해 단위행렬이 나오는지 확인하시오.

In [32]:
A = sales[:, :3]
A

det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)

In [34]:
inv_A

array([[ 0.0760181 , -0.04162896,  0.00271493],
       [-0.1040724 ,  0.06651584, -0.01085973],
       [ 0.00452489, -0.00723982,  0.01206637]])

In [37]:
A @ inv_A

array([[ 1.00000000e+00, -9.48893741e-16, -4.68375339e-17],
       [ 1.81625548e-15,  1.00000000e+00, -9.36750677e-17],
       [ 8.67361738e-16, -4.57966998e-16,  1.00000000e+00]])

총매출이 가장 높은 지점의 인덱스(argmax)와, 지점 순서대로의 누적 매출(cumsum)을 구하시오.

In [42]:
# 총매출이 가장 높은 지점의 인덱스(argmax)
total_sales = sales @ price
print(total_sales)
top_store_idx = total_sales.argmax()
print('가장 매출액이 높은 지점:', top_store_idx)

# 지점 순서대로의 누적 매출(cumsum)
total_sales.cumsum()

[ 765000 1260000 1082500]
가장 매출액이 높은 지점: 1


array([ 765000, 2025000, 3107500])