In [1]:
%pip install numpy
# 가상환경 내부에 설치할 경우 %를 앞에 붙임

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ----------------------- ---------------- 7.3/12.4 MB 41.2 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 32.5 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [9]:
# 행렬 합 (기존)
matrix_1=[[1,2],[3,4]]
matrix_2=[[5,6],[7,8]]

matrix_result = []
for i in range(len(matrix_1)):
    tmp= []
for j in range(len(matrix_1[i])):
    tmp.append(matrix_1[i][j]+matrix_2[i][j])
    matrix_result.append(tmp)
    print(matrix_result)

[[10]]
[[10, 12], [10, 12]]


In [11]:
# 행렬 합 (numpy)
matrix_result = np.array(matrix_1) + np.array(matrix_2)
print(matrix_result)

[[ 6  8]
 [10 12]]


In [12]:
# 행렬 내부 더하기
for i in range(len(matrix_1)):
    for j in range(len(matrix_1[i])):
        matrix_1[i][j] += 1
print(matrix_1)


[[2, 3], [4, 5]]


In [13]:
matrix_1 = np.array(matrix_1) + 1

In [ ]:
# numpy의 연산 속도 우위

import time
size = 10000000
# list
x = list(range(size))
y = list(range(size))
start_time = time.time()
z = [x[i]+y[i] for i in range(size)]
print('리스트 걸린시간', time.time() - start_time)
# adlist
x = np.arange(size)
y = np.arange(size)
start_time = time.time()
z = x+y
print('넘파이 걸린시간', time.time() - start_time)

리스트 걸린시간 1.1009860038757324
넘파이 걸린시간 0.12780308723449707


In [31]:
# 실습 01
# x=[1, 2, 3, 4, 5, 6, 7, 8, 9]
# y=[10, 20, 30, 40, 50, 60, 70, 80, 90]
'''위의 배열로 Numpy를 사용하여 3 X 3 행렬을 만든 뒤 행렬합과 행렬곱을 구해주세요.
결과:
[[11 22 33]
[44 55 66]
[77 88 99]]
[[300 360 420]
[660 810 960]
[1020 1260 1500]]'''

# import numpy as np
x=np.arange(1,10).reshape(3,3)
y=np.arange(10,100,10).reshape(3,3)
print(x,y)



[[1 2 3]
 [4 5 6]
 [7 8 9]] [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [25]:
x = np.arange(24).reshape(2, 3, 4)
print(x.shape, x.ndim, x.size)

(2, 3, 4) 3 24


In [36]:
x = np.arange(20).reshape(4, 5)
print(x[1:4,1:4])

[[ 6  7  8]
 [11 12 13]
 [16 17 18]]
